### ISSUE TITLE
the flash is very corrupted [nsfw]

### ISSUE THREAD

**Issue by kotenok2000** [lightspark/lightspark#581]
## In order to help us understand your issue, please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes `[ ]` relevant to your issue (like this: `[x]`)
- Please fill in the sections relevant to your issue and delete the rest.
- Use the *Preview* tab to see what your issue will actually look like

---

### What is the purpose of your issue?
- [ ] Site Support Request: Lightspark does not work correctly on a specific website.
- [x] Bug: Lightspark has the same problem across multiple websites or SWF files.
- [ ] Feature request: a request for new features or support for new platforms, *not sites or SWF files*.
- [ ] Question, Comment, or Suggestion
- [ ] If none of the above apply, check this box.

---

### The following sections should be filled in based on the purpose listed above. Erase any section (the contents between triple ---) that does not apply.

---

#### Provide the complete URL of the page with the issue here:
Warning: flash is NSFW.
https://www.furaffinity.net/view/10289971/
#### If it is possible to download the file and run it with the command line, please provide a link to the file here:
Warning: flash is NSFW.
https://d.facdn.net/art/jasonafex/1494749212/1365081298.jasonafex_wolfy-nail_tauren_jasonafex.swf
#### Provide the complete set of instructions required to reproduce the problem:

1. Load the page.
2. *Insert second action here*
3. *Insert third action, and so on*

#### What kind of failure is your issue?

- [ ] **Fault**: You receive a black window instead of the flash content with a white text such as ``We're sorry, Lightspark encountered an as yet unsupported Flash file``
- [ ] **Crash**: The window disappears or your browser crashes with a message such as ``A tab has crashed``
- [x] **Broken**: Lightspark shows something, but most of the file is not usable
- [ ] **Glitch**: Lightspark shows something and most of the file is usable, but things are missing or wrong compared to official Flash.
- [ ] **Performance**: Lightspark runs slow or uses lots of memory trying to play the file

#### Provide the Lightspark version

Output of ``lightspark -v``:
```
 Lightspark version 0.8.3-git Copyright 2009-2013 Alessandro Pignotti and others
```

#### What operating system are you are running on?

- [x] Windows 7, 8 or 10
- [ ] Windows XP, Vista or older
- [ ] Linux: *<specify distro and version here, such as Ubuntu 18.04>*
- [ ] Mac OS X: *<specify version here, such as 10.8.1>*
- [ ] Other: *<specify OS and version here>*

#### How are you are running Lightspark?

- [ ] Browser plugin for Chrome or Chromium: *<specify Chromium version here>*
- [ ] Browser plugin for Waterfox: *<specify Waterfox version here>*
- [ ] Browser plugin for other browser: *<specify browser and version here>*
- [x] Lightspark executable on the command line

#### Which of these actions you have taken to help debug the problem?

- [ ] I attached a screen shot of the problem to this issue
- [ ] I have a backtrace listing and pasted it in the bottom section of this issue (*hint: hitting Ctrl-C after a crash will copy it to the clipboard*)
- [x] I have reproduced the problem using the Lightspark command line executable
- [x] I ran `lightspark -l 4` on the command line and am attaching logs to this issue (*hint: if they are too big, zip them*)
[lightspark.log.zip](https://github.com/lightspark/lightspark/files/5650993/lightspark.log.zip)

---

### If this issue is a *feature request*:

Identify the type of request:

- [ ] Support for a new OS: *<name the operating system here>*
- [ ] Support for a new browser: *<name the operating system here>*
- [ ] Support for embedding in an application: *<name the application here>*

---

### If this issue is a *question, comment, or suggestion*:

Identify the subject of this issue:

- [ ] The documentation of how to use Lightspark, including the wiki
- [ ] The build instructions to compile Lightspark from source
- [ ] The project and how it is managed (people, process, and so on)
- [ ] Other subject matter not listed

---

### Description of your issue

This swf does not show video. Also rmb context menu does not open.

**Comment by JohnSmith2007** [comment]
It's funny that you're using it for Jasonaex's SWFs, because i'm using it for the same thing.

**Comment by JousterL** [comment]
By default they don't even render in 0.8.4 past the start screen.
I don't know how much this helps (if at all), but here goes:
If you go into the ThrowError function in /src/scripting/toplevel/Error.h and exclude the following three IDs from the throw
- 1009
- 1010
- 1070

To do the exclude, replace the function with something like this
`if(errorID==1009||errorID==1010||errorID==1070){}
 else { throw Class<T>::getInstanceS(getSys(),message, errorID); }`

You can get it to run, somewhat. It'll render the initial photo and the tweens will glitch with purple textures, but it's definitely trying.
It also creates a wicked memory leak (to the tune of a GB every 10 seconds).
Unfortunately I quite literally have no idea what I'm doing when it comes to the Flash state machine, so debugging what actually needs to change to resolve the exceptions instead of bypassing them is beyond my ken.

**Comment by JousterL** [comment]
Playback works great with the new commit, without the tweening glitches. However, the memory leak is still there. Would you prefer a new issue be opened to track it?

**Comment by dbluelle** [comment]
I've fixed the memory leak in 50aad158ebe401c8e7a7398a5bfd5620d7291118, so no new issue needed.

**Comment by JousterL** [comment]
It's much better, but there's still a leak somewhere. To the tune of about 600MB every 30 seconds. Seems to happen on a reset of state (the screen flashes green for a second before the scene repeats), and it dumps a fair bit into the console about audio.

`[mp3 @ 0x7f71dc736ac0] invalid concatenated file detected - using bitrate for duration
INFO: AUDIO DEC: Audio sample rate 44100
INFO: AUDIO DEC: Audio channels 2
[mp3float @ 0x7f71dc737540] Could not update timestamps for skipped samples.
ERROR: resampling failed
INFO: AUDIO DEC: Audio sample rate 44100
INFO: AUDIO DEC: Audio channels 2
INFO: AUDIO DEC: Initial timestamp 0
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
`

**Comment by dbluelle** [comment]
I couldn't exactly reproduce your problem.
However I reworked the whole embedded video handling, so that it uses less cpu and memory, maybe it helps with your issue, too.

**Comment by JousterL** [comment]
Much like the originator's flash file, there's an initial screen with a single play button to trigger the video file.
I can confirm that the new commit (9e39161) has resolved the memory leak, but at a significant performance penalty. 50aad15 runs video at 28-36fps, and 9e39161 runs it at 1-3fps. 

I've generated cachegrind and callgrind profiles for both commits in Debug builds utilizing valgrind, and attached below.

Looking at the cachegrind profiles, the only difference I can see is extra time spent in YUV420ChannelsToYUV0BufferWithAlpha, whereas looking at the callgrind profiles shows 9e39161 spending a fair amount of time in DefineVideoStreamTag.

[lightspark.zip](https://github.com/lightspark/lightspark/files/6103214/lightspark.zip)


On a smaller note, it looks like the caching code doesn't discard for new scenes. This can be reproduced by clicking the "Change Speed" button. This isn't as big of an issue, but it does mean that progressing a scene will eventually force Lightspark to reach a maximal amount of RAM utilization (where all scenes are cached).

**Comment by dbluelle** [comment]
I've done a little more tweaks to reduce memory usage.
There is a tradeoff between RAM usage and cpu usage: If we cache the decoded frames (like we do now), lightspark uses more RAM but doesn't have to decode every frame everytime when displaying one. A better solution may be using hardware decoding where possible, but I've not yet checked how to implement that using ffmpeg.

**Comment by JousterL** [comment]
*nods* Figured as much. Didn't know if the Flash state machine was granular enough to cache perhaps scene and scene+1 while discarding scene-1.

I just tried using bc92bd4 and can confirm that while performance is back, the leak is too. After stabilizing in memory size once the scene renders, it begins to consume around 200MB every 20-25 seconds the video plays. Going back through the commits, it looks like the leak was reintroduced in cd9a16b

The red line on the memory chart is where I clicked Play.
![MemoryLeak](https://user-images.githubusercontent.com/439681/110667652-600c7600-81c2-11eb-9bd4-436f9f68af7c.png)

**Comment by dbluelle** [comment]
Hmm, on my machine after clicking play the memory usage increases until the movie is cached, but doesn't increase afterwards...
The problem with this specific file is that it replays the movie from start all the time, (until you click the "change speed" button).
So if we don't cache the frames they have to be decoded all the time, which uses a lot of cpu time and leads to framedrops (the swf file has a framerate of 60 fps) .

**Comment by JousterL** [comment]
As best as I can tell (while watching the process in htop sorted by Mem usage), there's always a hitch/pause in playback, and right after that hitch the memory usage spikes. I can see a thread starting and then disappearing, so I'm wondering if it's got something to do with it replaying the movie from start? It's doing the same thing with my file as it does with the file the reporter provided, but I'm at a loss for what else I can provide to assist in debugging.

**Comment by JousterL** [comment]
I chased it down as far as I could using gdb, but it's getting into the events subsystem where I rapidly get lost. Here's where I was able to trace it:

- Each time the movie is replayed, it calls VideoDecoder::setSize three times. On every ninth execution of this, either the second or third time this is called, the program stalls for a second and the memory usage increases.
- Tracing within this 9.b or 9.c call, it gets as far as ABCVm::Run. Within this loop, we run 9 times through chronometer.checkpoint. On -this- 9th iteration (within the 28th or 29th call to setSize) the function th->handleFrontEvent() triggers the memory increase.
- Tracing within THIS call and stepping into handleEvent(e) gets to e.second->as<WaitableEvent>()->signal(); which triggers the memory increase. Querying e.second->getEventType() returns a lightspark::IDLE_EVENT.
- Tracing through here gets to getSys()->sendMainSignal(); which in turn invokes tls_get(tls_system). Upon returning "ret" is when the memory increase occurs.

At this point I stopped debugging because I feel like the issue is with a specific frame, rather than a problem with the Flash execution VM.

So, to paraphrase: Every 28th or 29th call (it varies) to setSize, on the 9th IDLE_EVENT frame within this call, once it's processed, lightspark consumes an additional 200MB.

My only other observation is that it displays the FPS right after the memory increases. I commented out that section hoping it had something to do with the increase, but no luck.

The reporter's file does the same behavior, but only every 14 to 15 times setSize is called, which makes sense as his file only calls it one to two times each time the movie resets itself. I'll include a link below to my file in case the differences allow this to be replicated.
https://d.furaffinity.net/download/art/jousterl/1405946010/1405946010.jousterl_1405925576.jasonafex_scappo_slime_girl_jasonafex.swf

**Comment by dbluelle** [comment]
I've reworked the decoding (again) and now it doesn't cache all decoded frames anymore.
This significantly reduces memory usage.
However there still seems to be a memory leak somewhere, as memory usage still increases slowly over time.

**Comment by JousterL** [comment]
The newest commit significantly decreases the frequency of the leak. I'm only seeing it jump 200MB every 60 seconds or so now. 
If you're just playing the video, it's still timed to leak on the 28th/29th call to VideoDecoder::setSize. However, it's less reliably able to hit inside a debugger (I'm setting the breakpoint there and continuing 24 times to see the bug trigger).

I -think- I was able to extract the frame data for the bad frame, and have attached it to this thread. Just remove the .txt extension. Basically, I assumed the bug was going to hit, ran until the context was in FFMpegVideoDecoder::decodeData, converted the datalen value to hex and added it to the address for data to get the ending address, then dumped the memory in that block. I then continued execution to validate that that frame was the issue, and confirmed that memory increased once m_sys->flushInvalidationQueue(); ran inside ABCVm::handleFrontEvent.

I hope it helps. Thank you for the efforts to resolve this leak!
[frame.txt](https://github.com/lightspark/lightspark/files/6131669/frame.txt)

**Comment by JousterL** [comment]
To be as precise as possible... using GDB, it's exactly 24 iterations against VideoDecoder:;setSize. It gets to the flushInvalidationQueue(), runs through the while(!cur.isNull()) loop three times, and then invokes renderThread->signalSurfaceRefresh(). This in turn sends event.signal() which calls SDL_SemPost(sem). Stepping here doesn't resolve, so this is as far as it can be tracked.

**Comment by JousterL** [comment]
I was able to catch the flaw by looking at the memory map of the process as it's running. Every time it bugs, it spawns a new /dev/dri/renderD128 of size 256MB.
![lightsparkDRI](https://user-images.githubusercontent.com/439681/111015797-7a9d4580-83a2-11eb-83d1-e676d404a977.png)
I don't know if this is as simple as adding a check into the RenderThread to see if a renderer is already allocated, and if so, skip the initialization.

**Comment by JousterL** [comment]
So it's a pretty ugly kludge, but I was able to modify the /src/backend/rendering.cpp to rebuild the largeTextures.bitmap once it fills up, and then reattempt the allocateChunkOnTexture loop. No memory leak. Side effect is that the Change Speed texture gets glitchy, probably because I'm deleting it while it's still in use and not reloading the GL Context properly.

[rendering.txt](https://github.com/lightspark/lightspark/files/6135601/rendering.txt)

Change the .txt to .cpp and compile with it, and the leak is remediated. I'll still welcome your expert eye on a better way to handle this (either solving the actual problem of the reallocated textures, or a cleaner way of discarding unused texture chunks and defragmenting the largeTexture structure).

**Comment by dbluelle** [comment]
Sorry, but I still can not reproduce your problem.
I've committed a fix so that the videodecoder is deleted after the last frame of the video is displayed, so that it will be constructed again when the video is replayed from the first frame. Maybe that helps in your case.

**Comment by JousterL** [comment]
Still encountering the leak unfortunately. I'll probably just limp along with my kludge, but in case it helps for reproducibility, here's largeTextures at the beginning of the program and then when the bug triggers:
![largetexture](https://user-images.githubusercontent.com/439681/111196416-27e7a780-85b5-11eb-83f6-5d8829963d18.png)

Thanks for the efforts to try to resolve anyway!

**Comment by JousterL** [comment]
I was able to solve the leak much more cleanly, using your commit 86c2d0c as a starting point. The issue is that when you signal to destroy the embeddedVideoDecoder, you don't release the texture for the screen.
Adding this line after if (embeddedVideoDecoder) on line 161 of /src/scripting/flash/media/flashmedia.cpp fixes the problem.
`getSystemState()->getRenderThread()->releaseTexture(embeddedVideoDecoder->getTexture());`

**Comment by dbluelle** [comment]
Good catch!
I've included that at another position in my latest commit, so that this also works for streamed video and for bitmaps.
I've also reduced the overall memory usage, so that it looks ok now on my machine.

**Comment by JousterL** [comment]
Looks great. I've let it run through around 1300 loops and it's only leaked 31MB of memory (in 1MB renderD128 buffers). So I'd say that's solved.

Only other issue I'm running into is that there's a deadlock somewhere. Sometimes it's after ten loops, sometimes after a thousand, but the entire VM will stall out on terminated.wait(). Is there a way to set a timeout and destroy it regardless if it deadlocks for too long?

Full call stack is below:
```
#0  futex_abstimed_wait_cancelable (private=0, abstime=0x0, clockid=0, expected=0, futex_word=0x5555555bf510)
    at ../sysdeps/nptl/futex-internal.h:320
#1  do_futex_wait (sem=sem@entry=0x5555555bf510, abstime=0x0, clockid=0) at sem_waitcommon.c:112
#2  0x00007ffff471ac58 in __new_sem_wait_slow (sem=0x5555555bf510, abstime=0x0, clockid=0) at sem_waitcommon.c:184
#3  0x00007ffff72c0272 in  () at /lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#4  0x00007ffff7517f63 in lightspark::Semaphore::wait() (this=0x5555555bf7f8)
    at /home/test/Downloads/lightspark/src/threading.cpp:51
#5  0x00007ffff74c37e3 in lightspark::SystemState::destroy() (this=0x5555555bf7c0)
    at /home/test/Downloads/lightspark/src/swf.cpp:617
#6  0x000055555555d5b5 in main(int, char**) (argc=2, argv=0x7fffffffe068) at /home/test/Downloads/lightspark/src/main.cpp:520
```

**Comment by dbluelle** [comment]
Yes, there still is a memory leak somewhere, but I think it's not in the video handling.

**Comment by JousterL** [comment]
Apologies, I meant the 31MB more as an observation. I think that for the average use case someone isn't going to watch a looping Flash video for hours on end, so the leak is minimal enough that it can (at least for now) be ignored.

I am running into an eventual Deadlock in the program though. I elided it out of my earlier comment because I couldn't reproduce with -l 4 parameters, but I left it running overnight and finally got a capture. I've attached it below as well as a list of where all the threads are when it happens. As it's a Deadlock, I don't think it's going to be a quick solve, but just wanted to bring it to your attention. I can open a new issue if you would prefer.

Interestingly, the "Window Resize" detection code still works, even though the entire FlashVM is hung and the process has to be killed when it goes into this state.

[L4 Log.txt](https://github.com/lightspark/lightspark/files/6165622/L4.Log.txt)
[threads.txt](https://github.com/lightspark/lightspark/files/6165623/threads.txt)

**Comment by dbluelle** [comment]
Hmm, "window resize" means that at least  the rendering thread is still running normally, but it's hart to diagnose without a reproducible case.

**Comment by JousterL** [comment]
Yeah. It's too variable for me to pin down in GDB, and probably based on some specific system state or a race. I should note that the actual video doesn't resize, it just recognizes the window resized. Anyway, when I took a core dump of the hung state it came out to 2.2GB, which is a pretty significant increase over the text threads, so I agree that reproducibility is going to be a challenge.

At any rate, thank you for the work you have done, it's taken the files from barely render-able to absolutely functional!
