### ISSUE TITLE
Hero Fighter - unsupported error

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#583]
[SWF](https://drive.google.com/file/d/1sP0U7bz2XWSgZrYW1Qrubd9ooRFXszM-/view?usp=sharing)
Tested on current master (2e94c44bf617d55e27436024fd2d4a5a1116657c)

The error is a bit long-winded to reproduce, so I recorded a [video demonstrating it](https://youtu.be/W3hDyL1JcsA).

[Here](https://github.com/lightspark/lightspark/files/5670952/hf.log) is the terminal output from that recording.

**Comment by MangaD** [comment]
This is likely related to a whole bunch of errors that show up when starting the game. Pasting here a fraction of the log:

> INFO: throwing exception:1014 Error #1014: Class flex.messaging.io.ArrayCollection could not be found.
    at Class/init()
    at _Console_mx_managers_SystemManager/kickOff()
    at _Console_mx_managers_SystemManager/preloader_completeHandler()
    at mx.preloaders::Preloader/timerHandler()

> INFO: throwing exception:1014 Error #1014: Class flex.messaging.io.ArrayList could not be found.
    at Class/init()
    at _Console_mx_managers_SystemManager/kickOff()
    at _Console_mx_managers_SystemManager/preloader_completeHandler()
    at mx.preloaders::Preloader/timerHandler()

> INFO: throwing exception:1014 Error #1014: Class flex.messaging.config.ConfigMap could not be found.
    at Class/init()
    at _Console_mx_managers_SystemManager/kickOff()
    at _Console_mx_managers_SystemManager/preloader_completeHandler()
    at mx.preloaders::Preloader/timerHandler()

> INFO: throwing exception:1014 Error #1014: Class flex.messaging.messages.AcknowledgeMessage could not be found.
    at Class/init()
    at _Console_mx_managers_SystemManager/kickOff()
    at _Console_mx_managers_SystemManager/preloader_completeHandler()
    at mx.preloaders::Preloader/timerHandler()

> INFO: throwing exception:1014 Error #1014: Class DSK could not be found.
    at Class/init()
    at _Console_mx_managers_SystemManager/kickOff()
    at _Console_mx_managers_SystemManager/preloader_completeHandler()
    at mx.preloaders::Preloader/timerHandler()

> INFO: throwing exception:1014 Error #1014: Class flex.messaging.messages.AsyncMessage could not be found.
    at Class/init()
    at _Console_mx_managers_SystemManager/kickOff()
    at _Console_mx_managers_SystemManager/preloader_completeHandler()
    at mx.preloaders::Preloader/timerHandler()

> INFO: throwing exception:1014 Error #1014: Class DSA could not be found.
    at Class/init()
    at _Console_mx_managers_SystemManager/kickOff()
    at _Console_mx_managers_SystemManager/preloader_completeHandler()
    at mx.preloaders::Preloader/timerHandler()

> INFO: throwing exception:1014 Error #1014: Class flex.messaging.messages.CommandMessage could not be found.
    at Class/init()
    at _Console_mx_managers_SystemManager/kickOff()
    at _Console_mx_managers_SystemManager/preloader_completeHandler()
    at mx.preloaders::Preloader/timerHandler()

> INFO: throwing exception:1014 Error #1014: Class DSC could not be found.
    at Class/init()
    at _Console_mx_managers_SystemManager/kickOff()
    at _Console_mx_managers_SystemManager/preloader_completeHandler()
    at mx.preloaders::Preloader/timerHandler()

> INFO: throwing exception:1014 Error #1014: Class flex.messaging.messages.ErrorMessage could not be found.
    at Class/init()
    at _Console_mx_managers_SystemManager/kickOff()
    at _Console_mx_managers_SystemManager/preloader_completeHandler()
    at mx.preloaders::Preloader/timerHandler()

> INFO: throwing exception:1014 Error #1014: Class flex.messaging.messages.HTTPMessage could not be found.
    at Class/init()
    at _Console_mx_managers_SystemManager/kickOff()
    at _Console_mx_managers_SystemManager/preloader_completeHandler()
    at mx.preloaders::Preloader/timerHandler()

> INFO: throwing exception:1014 Error #1014: Class flex.messaging.messages.MessagePerformanceInfo could not be found.
    at Class/init()
    at _Console_mx_managers_SystemManager/kickOff()
    at _Console_mx_managers_SystemManager/preloader_completeHandler()
    at mx.preloaders::Preloader/timerHandler()

> INFO: throwing exception:1014 Error #1014: Class flex.messaging.io.ObjectProxy could not be found.
    at Class/init()
    at _Console_mx_managers_SystemManager/kickOff()
    at _Console_mx_managers_SystemManager/preloader_completeHandler()
    at mx.preloaders::Preloader/timerHandler()

> INFO: throwing exception:1014 Error #1014: Class mx.skins.halo::HaloBorder could not be found.
    at Class/getDefinition()
    at Console/isBorderNeeded()
    at Console/createBorder()
    at Console/styleChanged()
    at Console/styleChanged()
    at mx.managers.systemClasses::ChildManager/addingChild()
    at mx.managers.systemClasses::ChildManager/initializeTopLevelWindow()
    at _Console_mx_managers_SystemManager/initializeTopLevelWindow()
    at _Console_mx_managers_SystemManager/kickOff()
    at _Console_mx_managers_SystemManager/preloader_completeHandler()
    at mx.preloaders::Preloader/timerHandler()

**Comment by MangaD** [comment]
Why was this issue closed?

**Comment by dbluelle** [comment]
It was fixed in commit 73a110d.
Github automatically closes an issue if you add a line "fixes #issue" into the commit message.

**Comment by MangaD** [comment]
@dbluelle Thanks a lot! I still see the exceptions being throw though. Example: `Class flex.messaging.io.ArrayCollection could not be found.`

Should I make a new issue for them?

**Comment by eiglow** [comment]
Feel free to open another issue. Sometimes, exceptions are thrown but things still work properly, but you may as well open an issue so that we can investigate.
